name: Waystones Conversion

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: wherethehellimat
      run: |
        ls
        echo "---"
        ls ../
        echo "---"
        ls ../..
        echo "---"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Waystones Conversion
      run: python markdowncon.py
