name: Waystones Conversion

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install update
      run: sudo apt-get update && sudo rm -rf ./waystones.md

    - name: Debug Repository Contents
      run: |
        ls -R $GITHUB_WORKSPACE
        echo "---"
        cd $GITHUB_WORKSPACE
        ls -R

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Waystones Conversion
      run: python markdowncon.py
      
    - name: Clean up
      run: sudo rm -rf ./cache
      
    - name: Upload Waystones.md as artifact
      uses: actions/upload-artifact@v2
      with:
        name: waystones-artifact
        path: ./waystones.md
