name: Waystones Conversion

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install curl
      run: sudo apt-get update && sudo apt-get install -y curl

    - name: Get files
      run: |
        curl -OL https://raw.githubusercontent.com/MidnightTale/hynse-classic/main/requirements.txt
        curl -OL https://raw.githubusercontent.com/MidnightTale/hynse-classic/main/waystones.json
        curl -OL https://raw.githubusercontent.com/MidnightTale/hynse-classic/main/markdowncon.py

    - name: Debug Repository Contents
      run: |
        ls -R $GITHUB_WORKSPACE
        echo "---"
        cd $GITHUB_WORKSPACE
        ls -R

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Waystones Conversion
      run: python markdowncon.py
